import fs from 'node:fs';
import type { Position } from '../../src/engine/types.ts';
import { applyGeneratedAction, initialPosition, legalActions } from '../../src/engine/position.ts';
import { Game } from '../../src/match/game.ts';
import Match from '../core/MatchSpec.bend';

/** Values crossing the Bend loader boundary are deliberately kept explicit. */
export type BendValue = Record<string, unknown> | unknown[] | string | number | bigint | boolean | null;
export type BendList = BendValue;

export function fail(message: string): never {
  throw new Error(message);
}

export function assert(condition: unknown, message: string): asserts condition {
  if (!condition) fail(message);
}

export function describe(value: unknown): string {
  try {
    return JSON.stringify(value, (_key, item) => typeof item === 'bigint' ? `${item}n` : item);
  } catch {
    return String(value);
  }
}

export function asObject(value: unknown, context: string): Record<string, unknown> {
  if (typeof value !== 'object' || value === null || Array.isArray(value)) {
    fail(`${context}: expected tagged object, got ${describe(value)}`);
  }
  return value as Record<string, unknown>;
}

export function bendBool(value: unknown, context = 'Bool'): boolean {
  if (typeof value === 'boolean') return value;
  const object = asObject(value, context);
  if (object.$ === 'True') return true;
  if (object.$ === 'False') return false;
  fail(`${context}: expected True/False, got ${describe(value)}`);
}

export function bendNat(value: unknown, context = 'Nat'): bigint {
  if (typeof value === 'bigint') return value;
  if (typeof value === 'number' && Number.isSafeInteger(value) && value >= 0) return BigInt(value);
  fail(`${context}: expected non-negative Nat, got ${describe(value)}`);
}

export function bendU32(value: unknown, context = 'U32'): number {
  const result = typeof value === 'bigint' ? Number(value) : value;
  if (typeof result !== 'number' || !Number.isSafeInteger(result) || result < 0 || result > 0xffff_ffff) {
    fail(`${context}: expected U32, got ${describe(value)}`);
  }
  return result;
}

/** Construct the ordinary Con/Nil list values generated by Bend 2. */
export function bendList(values: readonly unknown[]): BendValue {
  let result: BendValue = { $: 'Nil' };
  for (let index = values.length - 1; index >= 0; index -= 1) {
    result = { $: 'Con', head: values[index], tail: result };
  }
  return result;
}

export function fromBendList(value: unknown, context = 'List'): unknown[] {
  if (Array.isArray(value)) return [...value];
  const result: unknown[] = [];
  let cursor: unknown = value;
  const seen = new Set<unknown>();
  for (;;) {
    if (seen.has(cursor)) fail(`${context}: cyclic list`);
    if (cursor === null || typeof cursor !== 'object') {
      fail(`${context}: expected Con/Nil, got ${describe(cursor)}`);
    }
    seen.add(cursor);
    const object = cursor as Record<string, unknown>;
    if (object.$ === 'Nil') return result;
    if (object.$ !== 'Con' || !Object.prototype.hasOwnProperty.call(object, 'head')
      || !Object.prototype.hasOwnProperty.call(object, 'tail')) {
      fail(`${context}: expected Con/Nil, got ${describe(cursor)}`);
    }
    result.push(object.head);
    cursor = object.tail;
  }
}

export function positionToBend(position: Position): Record<string, unknown> {
  return {
    $: 'Pos',
    board: bendList(position.board.map((piece) => piece < 0 ? Math.abs(piece) + 8 : piece)),
    holes: position.holes >>> 0,
    side: position.side === 1,
    rights: position.castling >>> 0,
    ep: position.ep_target < 0 ? 64 : position.ep_target >>> 0,
    epPawn: position.ep_pawn < 0 ? 64 : position.ep_pawn >>> 0,
    quiet: BigInt(position.halfmove),
    full: BigInt(position.fullmove),
  };
}

export function positionFromBend(value: unknown, context = 'Position'): Position {
  const object = asObject(value, context);
  if (object.$ !== 'Pos') fail(`${context}: expected Pos, got ${describe(value)}`);
  const board = fromBendList(object.board, `${context}.board`).map((piece, index) => {
    const code = bendU32(piece, `${context}.board[${index}]`);
    return code === 0 ? 0 : code >= 9 ? -(code - 8) : code;
  });
  const side = bendBool(object.side, `${context}.side`) ? 1 : -1;
  const ep = bendU32(object.ep, `${context}.ep`);
  const epPawn = bendU32(object.epPawn, `${context}.epPawn`);
  const quiet = bendNat(object.quiet, `${context}.quiet`);
  const full = bendNat(object.full, `${context}.full`);
  assert(board.length === 64, `${context}.board: expected 64 entries, got ${board.length}`);
  assert(ep === 64 || ep < 64, `${context}.ep: expected 0..64, got ${ep}`);
  assert(epPawn === 64 || epPawn < 64, `${context}.epPawn: expected 0..64, got ${epPawn}`);
  assert(quiet <= BigInt(Number.MAX_SAFE_INTEGER), `${context}.quiet is not safely representable in TS oracle`);
  assert(full <= BigInt(Number.MAX_SAFE_INTEGER), `${context}.full is not safely representable in TS oracle`);
  return {
    board,
    holes: bendU32(object.holes, `${context}.holes`),
    side,
    castling: bendU32(object.rights, `${context}.rights`),
    ep_target: ep === 64 ? -1 : ep,
    ep_pawn: epPawn === 64 ? -1 : epPawn,
    halfmove: Number(quiet),
    fullmove: Number(full),
  };
}

export function samePosition(left: Position, right: Position): boolean {
  return left.side === right.side
    && left.holes === right.holes
    && left.castling === right.castling
    && left.ep_target === right.ep_target
    && left.ep_pawn === right.ep_pawn
    && left.halfmove === right.halfmove
    && left.fullmove === right.fullmove
    && left.board.length === right.board.length
    && left.board.every((piece, index) => piece === right.board[index]);
}

export function assertPosition(expected: Position, actualValue: unknown, context: string): void {
  const actual = positionFromBend(actualValue, context);
  if (samePosition(expected, actual)) return;
  const fields = ['holes', 'side', 'castling', 'ep_target', 'ep_pawn', 'halfmove', 'fullmove'] as const;
  const differences = fields.filter((field) => expected[field] !== actual[field])
    .map((field) => `${field}: expected ${expected[field]}, got ${actual[field]}`);
  const boardDifferences = expected.board.flatMap((piece, index) => piece === actual.board[index]
    ? [] : [`board[${index}]: expected ${piece}, got ${actual.board[index]}`]);
  fail(`${context}: position mismatch (${[...differences, ...boardDifferences].join('; ')})`);
}

export function assertIds(expected: readonly number[], actualValue: unknown, context: string): void {
  const actual = fromBendList(actualValue, context).map((id, index) => bendU32(id, `${context}[${index}]`));
  assert(actual.length === expected.length,
    `${context}: expected ${expected.length} IDs, got ${actual.length}: ${describe(actual)}`);
  for (let index = 0; index < expected.length; index += 1) {
    assert(actual[index] === expected[index],
      `${context}: ID[${index}] expected ${expected[index]}, got ${actual[index]}`);
    if (index > 0) {
      assert(actual[index - 1] < actual[index],
        `${context}: IDs must be strictly increasing at ${index - 1}/${index}`);
    }
  }
}

export function assertOrderedIds(value: unknown, context: string): number[] {
  const ids = fromBendList(value, context).map((id, index) => bendU32(id, `${context}[${index}]`));
  assert(ids.length > 0, `${context}: legal action enumeration must not be empty`);
  for (let index = 1; index < ids.length; index += 1) {
    assert(ids[index - 1] < ids[index], `${context}: IDs must be strictly increasing at ${index - 1}/${index}`);
  }
  return ids;
}

export function functionFrom(modules: readonly [string, unknown][], names: readonly string[]): (...args: any[]) => any {
  for (const name of names) {
    for (const [label, module] of modules) {
      if (typeof module === 'object' && module !== null && typeof (module as Record<string, unknown>)[name] === 'function') {
        return (module as Record<string, (...args: any[]) => any>)[name];
      }
    }
  }
  const exports = modules.map(([label, module]) => `${label}=[${module && typeof module === 'object' ? Object.keys(module).join(', ') : typeof module}]`).join('; ');
  fail(`Bend API missing ${names.join('/')} (${exports})`);
}

export function unwrapStep(value: unknown, old: unknown): { accepted: boolean; position: unknown } {
  const object = (typeof value === 'object' && value !== null && !Array.isArray(value))
    ? value as Record<string, unknown> : null;
  if (object?.$ === 'Accepted') {
    const next = object.next ?? object.state;
    if (next === undefined) fail(`Accepted result has no next position: ${describe(value)}`);
    return { accepted: true, position: next };
  }
  if (object?.$ === 'Rejected') {
    const rejected = object.old ?? object.position ?? old;
    return { accepted: false, position: rejected };
  }
  return { accepted: true, position: value };
}

export function clonePosition(position: Position): Position {
  return { ...position, board: [...position.board] };
}

export function mutate(position: Position, change: (copy: Position) => void): Position {
  const copy = clonePosition(position);
  change(copy);
  return copy;
}

type MatchObject = Record<string, unknown>;

function matchObject(value: unknown, context: string): MatchObject {
  return asObject(value, context);
}

function command(tag: string, fields: MatchObject): MatchObject {
  return { $: tag, ...fields };
}

function matchResult(value: unknown, context: string): { accepted: boolean; match: MatchObject } {
  const result = matchObject(value, context);
  if (result.$ === 'Accepted') {
    return { accepted: true, match: matchObject(result.next, `${context}.next`) };
  }
  if (result.$ === 'Rejected') {
    return { accepted: false, match: matchObject(result.old, `${context}.old`) };
  }
  fail(`${context}: expected Accepted/Rejected, got ${describe(value)}`);
}

function matchRevision(match: MatchObject, context: string): bigint {
  return bendNat(match.revision, `${context}.revision`);
}

function matchActions(match: MatchObject, context: string): number[] {
  return fromBendList(match.actions, `${context}.actions`).map((id, index) => bendU32(id, `${context}.actions[${index}]`));
}

function assertOutcomeTag(match: MatchObject, expected: string | null, context: string): void {
  const outcome = matchObject(Match.outcome(match), `${context}.outcome`);
  if (expected === null) {
    assert(outcome.$ === 'None', `${context}: expected None outcome, got ${describe(outcome)}`);
    return;
  }
  assert(outcome.$ === 'Some', `${context}: expected Some(${expected}), got ${describe(outcome)}`);
  const value = matchObject(outcome.value, `${context}.outcome.value`);
  assert(value.$ === expected, `${context}: expected ${expected}, got ${describe(value)}`);
}

function assertMatchState(expected: MatchObject, actual: MatchObject, context: string): void {
  assertPosition(positionFromBend(expected.state, `${context}.expected.state`), actual.state, `${context}.state`);
  assert(matchRevision(expected, `${context}.expected`) === matchRevision(actual, `${context}.actual`),
    `${context}.revision: expected ${describe(expected.revision)}, got ${describe(actual.revision)}`);
  const expectedActions = matchActions(expected, `${context}.expected`);
  const actualActions = matchActions(actual, `${context}.actual`);
  assert(expectedActions.length === actualActions.length && expectedActions.every((id, index) => id === actualActions[index]),
    `${context}.actions: expected ${describe(expectedActions)}, got ${describe(actualActions)}`);
}

function customMatch(position: Position, policy: MatchObject): MatchObject {
  const bendPosition = positionToBend(position);
  const importer = (Match as unknown as Record<string, unknown>).from_position;
  assert(typeof importer === 'function', 'Match.from_position is required for imported-state conformance');
  const imported = importer(bendPosition, policy);
  const result = matchObject(imported, 'Match.from_position');
  assert(result.$ === 'Some', `Match.from_position rejected a conformance position: ${describe(imported)}`);
  return matchObject(result.value, 'Match.from_position.value');
}

function callMatch(name: string, fn: (...args: any[]) => unknown, ...args: any[]): unknown {
  try {
    return fn(...args);
  } catch (error) {
    fail(`${name} threw: ${String(error)}`);
  }
}

/** Deterministic checks for the match layer's revision and terminal boundary. */
export function runMatchInterop(): { checks: number } {
  const checks = { value: 0 };
  const prompt = { $: 'Prompt' };
  const start = matchObject(callMatch('Match.start(B)', Match.start, true, prompt), 'start');
  assertPosition(initialPosition('B'), start.state, 'Match.start(B).state');
  assert(matchRevision(start, 'start') === 0n, 'Match.start(B): revision must begin at zero');
  assert(matchActions(start, 'start').length === 0, 'Match.start(B): action history must begin empty');
  assertOutcomeTag(start, null, 'Match.start(B)');
  checks.value += 3;

  const first = matchResult(callMatch('Match.step(move)', Match.step, start,
    command('MoveCommand', { expected: 0n, action: 2025 })), 'move');
  assert(first.accepted, 'opening move 2025 must be accepted');
  const opening = initialPosition('B');
  const openingAction = legalActions(opening).find((action) => action.id === 2025);
  assert(openingAction !== undefined, 'TS oracle must contain opening move 2025');
  assertPosition(applyGeneratedAction(opening, openingAction), first.match.state, 'opening move state');
  const tsOpening = new Game('B', 'prompt');
  const tsFirst = tsOpening.step(2025);
  assertPosition(tsFirst.position, first.match.state, 'opening move TS match oracle');
  assert(matchRevision(first.match, 'opening move') === 1n, 'opening move revision must be one');
  assertMatchState(start, start, 'identity sanity');
  checks.value += 2;

  const stale = matchResult(callMatch('Match.step(stale)', Match.step, first.match,
    command('MoveCommand', { expected: 0n, action: 2035 })), 'stale');
  assert(!stale.accepted, 'stale revision command must be rejected');
  assertMatchState(first.match, stale.match, 'stale rejection');
  checks.value += 2;

  const undone = matchResult(callMatch('Match.step(undo)', Match.step, first.match,
    command('UndoCommand', { expected: 1n })), 'undo');
  assert(undone.accepted, 'undo after one move must be accepted');
  assertPosition(initialPosition('B'), undone.match.state, 'undo state');
  assert(matchRevision(undone.match, 'undo') === 2n, 'undo increments revision once');
  assert(matchActions(undone.match, 'undo').length === 0, 'undo removes the board action');
  checks.value += 4;

  const offered = matchResult(callMatch('Match.step(offer)', Match.step, first.match,
    command('OfferCommand', { expected: 1n, side: true })), 'offer');
  assert(offered.accepted, 'draw offer must be accepted at its revision');
  const agreed = matchResult(callMatch('Match.step(accept)', Match.step, offered.match,
    command('AcceptCommand', { expected: 2n, side: false })), 'accept');
  assert(agreed.accepted, 'opponent draw acceptance must be accepted');
  assertOutcomeTag(agreed.match, 'Agreed', 'agreement');
  const terminal = matchResult(callMatch('Match.step(terminal move)', Match.step, agreed.match,
    command('MoveCommand', { expected: 3n, action: 2035 })), 'terminal move');
  assert(!terminal.accepted, 'terminal match must reject board actions');
  assertMatchState(agreed.match, terminal.match, 'terminal inertness');
  checks.value += 4;

  const resigned = matchResult(callMatch('Match.step(resign)', Match.step,
    matchObject(callMatch('Match.start(resign)', Match.start, true, prompt), 'resign start'),
    command('ResignCommand', { expected: 0n, side: true })), 'resign');
  assert(resigned.accepted, 'resignation must be accepted at revision zero');
  assertOutcomeTag(resigned.match, 'WhiteResignedOutcome', 'resignation');
  checks.value += 2;

  let repeated = matchObject(callMatch('Match.start(repetition)', Match.start, true, prompt), 'repetition start');
  const repetitionIds = [20825, 20900, 20825, 20900];
  for (let index = 0; index < repetitionIds.length; index += 1) {
    const result = matchResult(callMatch(`Match.step(repetition ${index})`, Match.step, repeated,
      command('MoveCommand', { expected: BigInt(index), action: repetitionIds[index] })), `repetition ${index}`);
    assert(result.accepted, `repetition action ${repetitionIds[index]} must be accepted`);
    repeated = result.match;
  }
  assertOutcomeTag(repeated, 'Threefold', 'third repetition');
  const tsRepeated = new Game('B', 'prompt');
  for (const action of repetitionIds) tsRepeated.step(action);
  assert(tsRepeated.outcome()?.reason === 'threefold',
    `TS oracle expected threefold after reversal sequence, got ${describe(tsRepeated.outcome())}`);
  checks.value += repetitionIds.length + 1;

  const replayStart = matchObject(callMatch('Match.start(replay)', Match.start, true, prompt), 'replay start');
  const replayCommands = bendList(repetitionIds.map((action, expected) =>
    command('MoveCommand', { expected: BigInt(expected), action })));
  const replayed = matchObject(callMatch('Match.replay', Match.replay, replayCommands, replayStart), 'replay result');
  assert(matchRevision(replayed, 'replay') === 4n, 'replay must apply each accepted command exactly once');
  assert(matchActions(replayed, 'replay').every((id, index) => id === repetitionIds[index]),
    'replay action history must preserve canonical IDs and order');
  checks.value += 2;

  const records = JSON.parse(fs.readFileSync(new URL('../../fixtures/conformance.json', import.meta.url), 'utf8')) as {
    fixtures: Array<{ name: string; record: { initial: Position } }>;
  };
  const autoFixture = records.fixtures.find((fixture) => fixture.name === 'auto_at_99');
  const mateFixture = records.fixtures.find((fixture) => fixture.name === 'mate_over_auto100');
  assert(autoFixture !== undefined && mateFixture !== undefined, 'match outcome fixtures are missing');

  const auto = customMatch(autoFixture.record.initial, { $: 'Auto100' });
  assertOutcomeTag(auto, null, 'auto100 at 99');
  const autoStep = matchResult(callMatch('Match.step(auto100)', Match.step, auto,
    command('MoveCommand', { expected: 0n, action: 5 })), 'auto100');
  assert(autoStep.accepted, 'auto100 fixture quiet action must be accepted');
  assertOutcomeTag(autoStep.match, 'Progress100', 'auto100 at 100');
  const tsAuto = new Game('B', 'auto100', autoFixture.record.initial);
  tsAuto.step(5);
  assert(tsAuto.outcome()?.reason === 'progress100',
    `TS oracle expected progress100, got ${describe(tsAuto.outcome())}`);
  checks.value += 3;

  const mate = customMatch(mateFixture.record.initial, { $: 'Auto100' });
  const mateStep = matchResult(callMatch('Match.step(mate)', Match.step, mate,
    command('MoveCommand', { expected: 0n, action: 14990 })), 'mate');
  assert(mateStep.accepted, 'mate-over-auto100 action must be accepted');
  assertOutcomeTag(mateStep.match, 'WhiteCheckmate', 'checkmate precedence');
  const tsMate = new Game('B', 'auto100', mateFixture.record.initial);
  tsMate.step(14990);
  assert(tsMate.outcome()?.reason === 'checkmate',
    `TS oracle expected checkmate precedence, got ${describe(tsMate.outcome())}`);
  checks.value += 2;

  const epFixture = records.fixtures.find((fixture) => fixture.name === 'en_passant');
  const pinnedFixture = records.fixtures.find((fixture) => fixture.name === 'pinned_en_passant');
  assert(epFixture !== undefined && pinnedFixture !== undefined, 'en-passant fixtures are missing');
  const epMatch = customMatch(epFixture.record.initial, prompt);
  const pinnedMatch = customMatch(pinnedFixture.record.initial, prompt);
  const epKeys = fromBendList(epMatch.keys, 'legal EP match keys');
  const pinnedKeys = fromBendList(pinnedMatch.keys, 'pinned EP match keys');
  assert(epKeys.length === 1 && pinnedKeys.length === 1, 'fresh imported matches must have one repetition key');
  const epKey = matchObject(epKeys[0], 'legal EP key');
  const pinnedKey = matchObject(pinnedKeys[0], 'pinned EP key');
  assert(bendU32(epKey.ep, 'legal EP key.ep') === epFixture.record.initial.ep_target,
    'a legal en-passant target must remain in the repetition key');
  assert(bendU32(epKey.epPawn, 'legal EP key.epPawn') === epFixture.record.initial.ep_pawn,
    'a legal en-passant pawn must remain in the repetition key');
  assert(bendU32(pinnedKey.ep, 'pinned EP key.ep') === 64,
    'a pinned en-passant target must be omitted from the repetition key');
  assert(bendU32(pinnedKey.epPawn, 'pinned EP key.epPawn') === 64,
    'a pinned en-passant pawn must be omitted from the repetition key');
  checks.value += 4;

  return { checks: checks.value };
}

if (import.meta.main) {
  console.log(JSON.stringify({ ok: true, ...runMatchInterop() }));
}
