import assert from 'node:assert/strict';
import P from './program';
import Layout from '../ui/Layout.bend';
const list=(xs:any[])=>xs.reduceRight((tail,head)=>({$: 'Con',head,tail}),{$:'Nil'});
const array=(xs:any)=>{const out=[];while(xs.$==='Con'){out.push(xs.head);xs=xs.tail;}return out;};
const event=(s:any,...es:any[])=>P.update(list(es),s);
const click=(s:any,square:number)=>P.board(false,s,square);
const act=(s:any,id:number)=>event(s,{$:'Activate',id});
const tick=(s:any,ms=240)=>event(s,{$:'Tick',ms});
const drain=(u:any)=>{let remaining=100;while(P.replaying(u.state)){assert.ok(remaining-->0,'bounded fixture replay completes');u=tick(u.state,16);}return u;};
let u=P.start('','',1024,768), s=u.state;
assert.equal(P.snapshot(s).meta.revision,0);
assert.equal(P.snapshot(s).frame.progress,16);
u=click(s,12);s=u.state;assert.equal(P.snapshot(s).frame.selected,12);
s=click(s,12).state;assert.equal(P.snapshot(s).frame.selected,64,'second piece click deselects');
s=click(s,16).state;assert.equal(P.snapshot(s).frame.tile,4);
s=click(s,17).state;assert.equal(P.snapshot(s).frame.tile,16,'same macro deselects from another square');
s=click(s,22).state;assert.equal(P.snapshot(s).frame.tile,16,'an empty tile with no legal Shift is not selectable');
s=click(s,42).state;assert.equal(P.snapshot(s).frame.tile,16,'a hole square is not selectable');assert.equal(P.snapshot(s).frame.selected,64);
s=click(s,52).state;assert.equal(P.snapshot(s).frame.selected,64,'an enemy piece is not selectable');
const original=P.record_text(s);
s=event(s,{$:'PointerDown',x:250,y:250,button:2,alt:false},{$:'PointerMove',x:290,y:290},{$:'PointerUp',x:290,y:290,button:2}).state;
assert.equal(P.view(s).yaw,338,'drag right decreases yaw');assert.equal(P.view(s).pitch,75,'drag down increases pitch');
assert.equal(P.record_text(s),original,'camera cannot mutate accepted journal');
s=event(s,{$:'Wheel',x:200,y:200,delta:-10000}).state;assert.equal(P.view(s).zoom,115);
s=event(s,{$:'Wheel',x:200,y:200,delta:10000}).state;assert.equal(P.view(s).zoom,75);
s=act(s,19).state;
const ids=array(P.legal(s));assert.ok(ids.length);
u=P.request_move(s,ids[0]);s=u.state;
assert.equal(P.snapshot(s).meta.revision,1);assert.equal(P.snapshot(s).moving,true);assert.equal(P.elapsed(s),1);
const accepted=P.record_text(s);assert.equal(JSON.parse(accepted).commands.length,1);
const progress=P.snapshot(s).frame.progress;
s=act(s,14).state;assert.equal(P.snapshot(s).frame.progress,progress,'camera preserves animation progress');
s=tick(s,120).state;assert.ok(P.snapshot(s).frame.progress>0);assert.ok(P.snapshot(s).frame.progress<16);
s=tick(s).state;s=act(s,3).state;assert.equal(P.snapshot(s).meta.revision,1);
assert.equal(P.snapshot(s).panels.menu,8);s=act(s,48).state;assert.equal(P.snapshot(s).meta.revision,2);
const record=JSON.parse(P.record_text(s));assert.equal(record.commands.length,2);assert.equal(record.commands[1].$,'UndoCommand');assert.equal(record.commands[1].expected,1);
const prefs={mode:'bot',humanWhite:false,botPaused:true,theme:1,sound:false,volume:0.42,view:{yaw:361,pitch:99,zoom:50}};
s=P.start('',JSON.stringify(prefs),640,800).state;
assert.equal(P.mode(s),2);assert.equal(P.snapshot(s).meta.botPaused,true);assert.equal(P.snapshot(s).preferences.volume,42);assert.equal(P.view(s).yaw,1);assert.equal(P.view(s).pitch,90);assert.equal(P.view(s).zoom,75);assert.equal(P.snapshot(s).mobile,true);
s=drain(event(s,{$:'FileText',text:accepted})).state;assert.equal(P.mode(s),0,'portable imported record is hotseat');assert.equal(P.snapshot(s).meta.revision,1);
u=P.start('{broken','',1024,768);s=u.state;assert.equal(P.snapshot(s).meta.recovery,true);assert.ok(array(u.effects).some((e:any)=>e.slot===2&&e.text==='{broken'));
u=act(s,6);assert.equal(P.snapshot(u.state).meta.revision,0);assert.ok(!array(u.effects).some((e:any)=>e.slot===0),'invalid raw save is not overwritten');
u=drain(event(s,{$:'FileText',text:JSON.stringify({...record,commands:[{$:'MoveCommand',expected:9,action:ids[0]}]})}));assert.equal(P.snapshot(u.state).meta.recovery,true,'replay rejects stale expected revision');
s=act(act(s,2).state,29).state;assert.equal(P.snapshot(s).meta.recovery,false,'explicit new match clears recovery');
// Revision-bound picking prevents stale displayed-view clicks from entering a newer game.
let stale=event(s,{$:'SquareInput',square:12,expected:99});assert.equal(stale.redraw,0);assert.equal(P.selected(stale.state),P.selected(s));
let exact=event(s,{$:'SquareInput',square:12,expected:0});assert.equal(P.selected(exact.state),12);
// Human Black starts with a scheduled bot move; a camera action cannot add a journal entry.
let bot=act(act(act(P.start('','',1024,768).state,2).state,32).state,29);
assert.ok(bot.after>0);assert.equal(P.mode(bot.state),2);
bot=tick(bot.state,16);assert.equal(P.snapshot(bot.state).meta.revision,1);assert.equal(P.snapshot(bot.state).moving,true);
bot=tick(bot.state);assert.ok(Layout.enabled(3,P.snapshot(bot.state),false),'Undo remains available with bot move history');
bot=act(bot.state,3);assert.equal(P.snapshot(bot.state).meta.botPaused,true);assert.equal(bot.after,0);
assert.ok(!Layout.enabled(3,P.snapshot(bot.state),false),'Undo disables when history is exhausted');
bot=act(bot.state,10);assert.ok(bot.after>0);
let draw=P.start('','',1024,768).state;draw=act(act(draw,6).state,49).state;assert.equal(P.snapshot(draw).meta.offer,1);draw=act(draw,8).state;assert.equal(P.snapshot(draw).meta.outcome,7);assert.equal(JSON.parse(P.record_text(draw)).commands.length,2);
const endedWithMove=act(act(act(tick(P.request_move(P.start('','',1024,768).state,ids[0]).state).state,6).state,49).state,8).state;
assert.ok(Layout.enabled(3,P.snapshot(endedWithMove),false),'Undo remains available after agreement when a move can be undone');
let resign=P.start('','',1024,768).state;resign=act(act(act(resign,7).state,51).state,42).state;assert.equal(P.snapshot(resign).meta.outcome,8);
let decline=act(act(act(P.start('','',1024,768).state,2).state,31).state,29).state;decline=act(decline,6).state;assert.ok(P.after(decline)>0);decline=tick(decline).state;assert.equal(P.snapshot(decline).meta.offer,0);assert.equal(JSON.parse(P.record_text(decline)).commands[1].$,'DeclineCommand');
let shift=P.start('','',1024,768).state;const shiftId=array(P.legal(shift)).find((id:any)=>id>=20480);assert.ok(shiftId!==undefined);shift=P.request_move(shift,shiftId).state;assert.equal(P.snapshot(shift).meta.revision,1);assert.equal(P.last(shift),shiftId);
let keyboard=P.set_focus(P.start('','',1024,768).state,56);keyboard=event(keyboard,{$:'KeyInput',code:38,down:true,alt:false,ctrl:false,shift:false}).state;assert.equal(P.focus(keyboard),56,'top rank arrow preserves file');keyboard=P.set_focus(keyboard,7);keyboard=event(keyboard,{$:'KeyInput',code:40,down:true,alt:false,ctrl:false,shift:false}).state;assert.equal(P.focus(keyboard),7,'bottom rank arrow preserves file');
let muted=P.start('',JSON.stringify({sound:false}),1024,768).state;const mutedMove=P.request_move(muted,array(P.legal(muted))[0]);assert.ok(!array(mutedMove.effects).some((e:any)=>e.$==='Sound'));
// A finite kernel-valid near-promotion fixture exercises the actual choice/command path.
let promotion=P.start('','',1024,768).state;const promotionBoard=Array(64).fill(0);promotionBoard[0]=6;promotionBoard[63]=14;promotionBoard[49]=1;
const promotionPosition={...P.pos(promotion),board:list(promotionBoard),rights:0,ep:64,epPawn:64,quiet:0n,full:1n};
promotion=P.refreshed(promotion,{...P.game(promotion),initial:promotionPosition,state:promotionPosition,actions:list([]),states:list([promotionPosition]),keys:list([])});
const promotionIds=array(P.legal(promotion)).filter((id:any)=>id<20480&&Math.floor(id/320)===49&&Math.floor(id/5)%64===57);assert.equal(promotionIds.length,4);
promotion=P.destination(promotion,promotionIds[0]).state;assert.equal(P.snapshot(promotion).panels.menu,4);assert.equal(P.snapshot(promotion).meta.revision,0);promotion=act(promotion,41).state;assert.equal(P.snapshot(promotion).meta.revision,0,'the chosen promotion is staged before its commit');assert.equal(P.snapshot(promotion).staged,true);assert.equal(P.snapshot(promotion).panels.menu,0);assert.deepEqual(array(P.snapshot(promotion).frame.targets),[57],'the staged frame marks only its destination');promotion=tick(promotion,16).state;assert.equal(P.snapshot(promotion).meta.revision,1);assert.equal(array(P.pos(promotion).board)[57],2,'knight promotion accepted by kernel');
console.log('native-program: selection toggles, drag direction, camera journal inertness, accepted move/undo/replay, animation, preference restoration, and invalid record preservation passed (finite sequential JS tests)');

// Move/Undo cycles amplify replay cost without growing the visible board history.
const amplified=JSON.stringify({...record,commands:Array.from({length:6},(_,expected)=>expected%2===0?{$:'MoveCommand',expected,action:ids[0]}:{$:'UndoCommand',expected})});
const lastGood=tick(P.request_move(P.start('','',1024,768).state,ids[0]).state).state;
const lastGoodText=P.record_text(lastGood);
let pending=event(lastGood,{$:'FileText',text:amplified});
assert.equal(pending.after,16);assert.ok(P.replaying(pending.state));
assert.equal(P.replay_state(pending.state).value.done,0,'import dispatch executes no commands');
assert.equal(P.record_text(pending.state),lastGoodText);
for(let done=1;done<=6;done++){
  pending=event(pending.state,{$:'Tick',ms:16},{$:'Tick',ms:16},{$:'Tick',ms:16});
  assert.equal(P.replay_state(pending.state).value.done,done,'one replay command per dispatch even for batched ticks');
  assert.equal(P.record_text(pending.state),lastGoodText,'partial candidate is never installed');
  assert.ok(!array(pending.effects).some((e:any)=>e.$==='Store'&&e.slot===0));
  assert.equal(P.record_text(act(pending.state,3).state),lastGoodText,'Undo is frozen during replay');
  assert.equal(P.record_text(P.request_move(pending.state,ids[0]).state),lastGoodText,'moves are frozen during replay');
}
pending=tick(pending.state,16);assert.ok(!P.replaying(pending.state));
assert.equal(JSON.parse(P.record_text(pending.state)).commands.length,6);
assert.equal(P.snapshot(pending.state).meta.revision,6);
assert.ok(array(pending.effects).some((e:any)=>e.$==='Store'&&e.slot===0));
let interrupted=tick(event(lastGood,{$:'FileText',text:amplified}).state,16);
interrupted=act(act(interrupted.state,2).state,29);
assert.ok(!P.replaying(interrupted.state),'New Match cancels replay');
assert.equal(P.snapshot(tick(interrupted.state).state).meta.revision,0);
let replaced=tick(event(lastGood,{$:'FileText',text:amplified}).state,16);
replaced=drain(event(replaced.state,{$:'FileText',text:accepted}));
assert.equal(P.snapshot(replaced.state).meta.revision,1,'subsequent Import replaces pending candidate');
let failed=drain(event(lastGood,{$:'FileText',text:JSON.stringify({...record,commands:[record.commands[0],{$:'UndoCommand',expected:99}]})}));
assert.equal(P.record_text(failed.state),lastGoodText,'late rejection preserves last good game');
assert.ok(P.snapshot(failed.state).meta.recovery);assert.ok(!P.replaying(failed.state));
assert.ok(array(failed.effects).some((e:any)=>e.slot===2));
const boot=drain(P.start(accepted,JSON.stringify(prefs),1024,768));
assert.equal(P.mode(boot.state),2,'saved startup retains bot preferences');
assert.equal(P.snapshot(boot.state).meta.botPaused,true);
console.log('incremental replay: bounded batched ticks, atomic install, frozen commands, cancellation, replacement, recovery and boot preferences passed');
