import assert from 'node:assert/strict';
import P from './program';
const list=(xs:any[])=>xs.reduceRight((tail,head)=>({$:'Con',head,tail}),{$:'Nil'});
const array=(xs:any)=>{const out=[];while(xs.$==='Con'){out.push(xs.head);xs=xs.tail;}return out;};
const event=(s:any,...es:any[])=>P.update(list(es),s);
const flags={$:'Reminder',white:false,black:false};
let r=P.reminder_flags(flags,99n,true,true);assert.deepEqual(r,flags);
r=P.reminder_flags(r,100n,true,true);assert.equal(r.white,true);assert.equal(r.black,false);
r=P.reminder_flags(r,101n,true,false);assert.equal(r.black,true);
assert.deepEqual(P.reminder_flags(r,110n,true,true),r,'uninterrupted episode keeps both acknowledgments');
assert.deepEqual(P.reminder_flags(r,0n,true,true),flags,'counter reset starts a new episode');
assert.deepEqual(P.reminder_flags(flags,100n,false,true),flags,'Auto and Off never mark prompted reminders');
const initial=P.start('','',1024,768).state;
const p={...P.pos(initial),quiet:99n};
const g={...P.game(initial),initial:p,state:p,states:list([p])};
const fixture=P.refreshed(initial,g);
const board=array(p.board);
const id=array(P.legal(fixture)).find((id:number)=>id<20480&&(board[Math.floor(id/320)]&7)===2);
assert.notEqual(id,undefined,'fixture has a legal quiet knight move');
const moved=P.request_move(fixture,id);
assert.equal(P.pos(moved.state).quiet,100n);
assert.match(P.snapshot(moved.state).panels.notice,/Black: 100 quiet actions/);
assert.ok(P.snapshot(moved.state).panels.notice.length*6<=480,'reminder fits the narrow pixel panel');
assert.equal(P.reminded(moved.state).black,true);
const dismissed=P.notice(moved.state,'');
assert.equal(P.snapshot(P.quiet_reminder(dismissed)).panels.notice,'','same player is not prompted again');
const whitePos={...P.pos(dismissed),side:true,quiet:101n};
const white=P.set_game(P.set_pos(dismissed,whitePos),{...P.game(dismissed),state:whitePos});
assert.match(P.snapshot(P.quiet_reminder(white)).panels.notice,/White: 100 quiet actions/);
const resetPos={...whitePos,quiet:0n};
const reset=P.quiet_reminder(P.set_game(P.set_pos(white,resetPos),{...P.game(white),state:resetPos}));
assert.deepEqual(P.reminded(reset),flags);
// A pending replay fixture isolates the same candidate fold used by real decoded records.
const text=P.record_text(moved.state);
let replay=event(initial,{$:'FileText',text}).state;
const pending=P.replay_state(replay).value;
replay=P.set_replay(replay,{$:'Some',value:{...pending,candidate:g}});
replay=event(replay,{$:'Tick',ms:16}).state;
assert.equal(P.replay_state(replay).value.reminded.black,true,'replay reconstructs current episode flags');
replay=event(replay,{$:'Tick',ms:16}).state;
assert.equal(P.reminded(replay).black,true,'complete install retains reconstructed flags');
assert.equal(P.snapshot(P.quiet_reminder(replay)).panels.notice,'','reload does not re-notify historical reminder');
for(const code of [72,77,78,83,85]){
  const ignored=event(initial,{$:'KeyInput',code,down:true,alt:true,ctrl:false,shift:false});
  assert.equal(ignored.redraw,0,'Alt+letter game shortcuts ignored');
  assert.deepEqual(P.snapshot(ignored.state),P.snapshot(initial));
}
const rotated=event(initial,{$:'KeyInput',code:39,down:true,alt:true,ctrl:false,shift:false});
assert.notEqual(P.view(rotated.state).yaw,P.view(initial).yaw,'Alt+arrow still controls camera');
const drag=event(initial,{$:'PointerDown',x:200,y:200,button:0,alt:true});
assert.equal(P.orbiting(drag.state),true,'Alt+drag still orbits');
console.log('quiet-reminder: episode flags, accepted quiet100 prompt, per-side suppression/reset, replay reconstruction, Alt shortcut guards passed');
