"""Rebuild portable golden fixtures and independently replay saved experiment records.

The goldens are generated by this reference, not an independent correctness oracle.
They are intended for cross-language parity tests, with human-readable scenario names.
"""
from __future__ import annotations
from dataclasses import asdict, replace
import hashlib
import json
from pathlib import Path
import sys
import time
import sliding_chess_sim as sim
from rift_core import Game, RULES_VERSION, action_data, action_id, position_data, position_hash

ROOT = Path(__file__).resolve().parents[1]


def sparse(pieces: dict[str, int], *, holes: tuple[int, int] = (5, 9), **kwargs) -> sim.State:
    """Create an explicit two-gap fixture; signed board has shape [64]."""
    board = [0] * 64
    for name, piece in pieces.items():
        board[(int(name[1])-1)*8 + ord(name[0])-97] = piece
    return sim.State(tuple(board), sum(1 << m for m in holes), **{"side": 1, "castling": 0, **kwargs})


def fixtures() -> list[dict]:
    """Return focused legal-action and complete successor-state parity fixtures."""
    cases = [
        ("opening_B", Game("B")), ("opening_C", Game("C")),
        ("cut_check_ray", Game(state=sparse({"e1": 6, "h8": -6, "e8": -4}, holes=(5, 11)))),
        ("restore_check_ray", Game(state=sparse({"a1": 6, "e8": -6, "e1": 4}, holes=(6, 11)))),
        ("shift_promotion", Game(state=sparse({"a1": 6, "h8": -6, "c6": 1}, holes=(13, 7), halfmove=73))),
        ("backward_pawn_ride", Game(state=sparse({"h1": 6, "h8": -6, "a3": 1}, holes=(0, 10)))),
        ("orthodox_castling", Game(state=sparse({"e1": 6, "a1": 4, "h1": 4, "e8": -6}, castling=3))),
        ("missing_castling_path", Game(state=sparse({"e1": 6, "a1": 4, "e8": -6}, holes=(1, 9), castling=2))),
        ("en_passant", Game(state=sparse({"a1": 6, "h8": -6, "e5": 1, "d5": -1}, holes=(4, 7), ep_target=43, ep_pawn=35))),
        ("pinned_en_passant", Game(state=sparse({"e1": 6, "h8": -6, "e8": -4, "e5": 1, "d5": -1}, holes=(4, 7), ep_target=43, ep_pawn=35))),
        ("prompt_at_99", Game(state=sparse({"a1": 6, "h8": -6, "g1": 2}, halfmove=99))),
        ("auto_at_99", Game(state=sparse({"a1": 6, "h8": -6, "g1": 2}, halfmove=99), draw_policy="auto100")),
        ("mate_over_auto100", Game(state=sparse({"f6": 6, "g6": 5, "h8": -6}, halfmove=99), draw_policy="auto100")),
    ]
    repetition = Game()
    for src, dst in ((4,5), (5,4), (4,5)):
        a = next(a for a in repetition.legal_actions() if isinstance(a, sim.Slide) and a.src_macro == src and a.dst_macro == dst)
        repetition.step(action_id(a))
    cases.append(("third_repetition_on_next_reverse", repetition))
    output = []
    for name, game in cases:
        children = []
        for action in game.legal_actions():
            child = Game.from_record(game.export_record())
            child.step(action_id(action))
            result = child.outcome()
            children.append({"action": action_data(action), "position": position_data(child.state),
                             "hash": position_hash(child.state), "outcome": asdict(result) if result else None})
        output.append({"name": name, "record": game.export_record(), "position_hash": position_hash(game.state),
                       "legal_action_ids": sorted(action_id(a) for a in game.legal_actions()), "children": children})
    return output


def main() -> None:
    """Verify recorded final positions/outcomes and regenerate deterministic parity fixtures."""
    start = time.monotonic()
    rows = json.loads((ROOT / "research/fresh/games.json").read_text())
    actions = 0
    for row in rows:
        game = Game.from_record(row["record"])
        outcome = game.outcome()
        assert (asdict(outcome) if outcome else None) == row["outcome"]
        assert (outcome is None) == row["truncated"]
        assert len(game.actions) == row["plies"]
        actions += len(game.actions)
    f = fixtures()
    (ROOT / "fixtures/conformance.json").write_text(json.dumps({"rules_version": RULES_VERSION, "fixtures": f}, indent=2))
    perfts = {}
    for depth in range(1, 5):
        perfts[str(depth)] = sim.perft(sim.initial_state(), depth)
    assert list(perfts.values()) == [20, 400, 8902, 197281]
    receipt = {"rules_version": RULES_VERSION, "replayed_games": len(rows), "replayed_actions": actions,
               "fixtures": len(f), "fixture_successors": sum(len(x["children"]) for x in f),
               "orthodox_opening_perft": perfts, "elapsed_seconds": round(time.monotonic()-start, 3),
               "scope": "Same-engine replay + orthodox regression, not independent variant proof or human playtesting"}
    (ROOT / "research/fresh/verification.json").write_text(json.dumps(receipt, indent=2))
    print(json.dumps(receipt, indent=2))


if __name__ == "__main__":
    main()
