/** Real Chromium module-worker fault, cancellation, damage and presentation checks. */
import {FrameWorkers} from '../../host/FrameWorkers.mjs';
import {TilePresenter} from '../../host/TilePresenter.mjs';
import {damageTiles} from '../../host/TileDamage.mjs';
const records=[],pools=[];let comparedBytes=0;
/** Fail immediately with a bounded diagnostic; no swallowed assertion failures. */
function assert(value,message){if(!value)throw new Error(message);}
/** Compare all bytes, not a thumbnail or a checksum. */
function equal(a,b,label){assert(a.length===b.length,`${label}: length`);for(let i=0;i<a.length;i++)if(a[i]!==b[i])throw new Error(`${label}: byte ${i}, ${a[i]} != ${b[i]}`);comparedBytes+=a.length;}
/** Independent full/tile RGBA oracle, with a moving object for damage tests. */
function reference(input,tile={x:0,y:0,size:32}){const result=new Uint8Array(tile.size*tile.size*4);for(let y=0;y<tile.size;y++)for(let x=0;x<tile.size;x++){const xx=x+tile.x,yy=y+tile.y,i=(y*tile.size+x)*4;let c=[(xx+input.seed)%256,(yy*7+input.seed)%256,input.seed%256,255];if(input.object)c=xx>=input.object.x&&xx<input.object.x+6&&yy>=3&&yy<12?[240,102,61,255]:[7,19,33,255];result.set(c,i);}return result;}
/** Construct test pools with explicit in-memory endpoints, leaving library logic intact. */
function pool(workers=2,options={}){const p=new FrameWorkers({size:32,tileSize:8,workers,taskModule:window.__fixtureURL,workerURL:window.__workerURL,timeoutMs:3000,...options});pools.push(p);return p;}
/** Assert rejection instead of treating an uncommitted result as an exception. */
async function rejects(promise,part){try{await promise;}catch(error){assert(String(error.message).includes(part),`wrong error: ${error.message}`);return;}throw Error('Expected rejection: '+part);}
/** Conservative footprint of one application object. */
function rect(x){return {left:x,top:3,right:x+6,bottom:12};}
try{
 assert(damageTiles(32,8,[]).length===0,'empty damage');assert(damageTiles(32,8,[rect(1),rect(1)]).length===2,'dedup');let invalid=false;try{damageTiles(31,8,[]);}catch{invalid=true;}assert(invalid,'invalid extent rejected');records.push('tile validation/dedup');
 const one=pool(1),four=pool(4);assert((await one.ready()).workers===1,'one real worker');assert((await four.ready()).workers===4,'four real workers');
 for(const seed of [1,37,199]){const [a,b]=await Promise.all([one.render({seed},{damage:seed===1?[]:undefined}),four.render({seed})]);equal(a.pixels,reference({seed}),'one');equal(b.pixels,a.pixels,'four');assert(a.metrics.fallbackTiles===0&&b.metrics.fallbackTiles===0,'must use actual workers');}
 records.push('real worker count 1/4 full reference parity, first partial request forced full');
 const captured={seed:17};const capture=four.render(captured);captured.seed=201;equal((await capture).pixels,reference({seed:17}),'input captured once');
 const copied=await four.render({seed:17});copied.pixels.fill(0);equal((await four.render({seed:17},{damage:[]})).pixels,reference({seed:17}),'caller output ownership');records.push('input snapshot and output ownership');
 const moving=pool(2);await moving.ready();await moving.render({seed:0,object:{x:0}});
 const stale=moving.render({seed:0,object:{x:12},delay:30},{damage:[rect(0),rect(12)]});const latest=moving.render({seed:0,object:{x:24}},{damage:[rect(12),rect(24)]});assert((await stale).reason==='superseded','superseded state');const good=await latest;equal(good.pixels,reference({seed:0,object:{x:24}}),'carried superseded damage');assert(good.metrics.carriedTiles>0,'carried damage is observable');
 const cancelled=moving.render({seed:0,object:{x:8},delay:30},{damage:[rect(24),rect(8)]});moving.cancel();assert((await cancelled).reason==='cancelled','cancel resolves');equal((await moving.render({seed:0,object:{x:16}},{damage:[rect(8),rect(16)]})).pixels,reference({seed:0,object:{x:16}}),'carried cancelled damage');records.push('superseded/cancelled damage carried from last-good frame');
 const canvas=document.createElement('canvas');canvas.width=canvas.height=32;const context=canvas.getContext('2d',{willReadFrequently:true}),presenter=new TilePresenter(context,32);presenter.present(good);equal(context.getImageData(0,0,32,32).data,good.pixels,'first Canvas upload');const moved=await moving.render({seed:0,object:{x:2}},{damage:[rect(16),rect(2),rect(24)]});presenter.present(moved);equal(context.getImageData(0,0,32,32).data,moved.pixels,'dirty Canvas upload');assert(presenter.present({committed:false}).uploads===0,'uncommitted Canvas no-op');records.push('actual Canvas2D full/dirty readback');
 const failing=pool(1,{fallback:async(input,tile)=>{if(input.fail)throw Error('deliberate fallback failure');return reference(input,tile);}});await failing.ready();await failing.render({seed:0,object:{x:0}});await rejects(failing.render({seed:0,object:{x:14},fail:true},{damage:[rect(0),rect(14)]}),'deliberate fallback failure');const recovered=await failing.render({seed:0,object:{x:24}},{damage:[rect(14),rect(24)]});equal(recovered.pixels,reference({seed:0,object:{x:24}}),'failed damage carried to fallback');assert(recovered.metrics.fallbackTiles>0,'fallback executed');records.push('failed generation preserves last-good and carries damage into recovery');
 const malformed=pool(1,{fallback:reference});await malformed.ready();const repaired=await malformed.render({seed:13,short:true});equal(repaired.pixels,reference({seed:13}),'malformed-length fallback');assert(malformed.failures.some(f=>f.error.includes('byte length')),'wrong-length worker quarantined');
 const wrong=pool(1,{workerURL:window.__badWorkerURL,fallback:reference});await wrong.ready();equal((await wrong.render({seed:23})).pixels,reference({seed:23}),'identity fallback');assert(wrong.failures.some(f=>f.error.includes('identity')),'wrong identity quarantined');records.push('malformed length and identity quarantined, bounded fallback');
 const setupFail=pool(1,{init:{fail:true},fallback:reference});const setupStatus=await setupFail.ready();assert(setupStatus.workers===0&&setupStatus.failures.length===1,'setup rejection status');equal((await setupFail.render({seed:4})).pixels,reference({seed:4}),'setup fallback');
 const setupHang=pool(1,{init:{hang:true},timeoutMs:250,fallback:reference});assert((await setupHang.ready()).workers===0,'init timeout');equal((await setupHang.render({seed:7})).pixels,reference({seed:7}),'timeout fallback');records.push('initialization failure and timeout');
 const tileHang=pool(1,{timeoutMs:500,fallback:reference});await tileHang.ready();const delayed=await tileHang.render({seed:19,delay:2000});equal(delayed.pixels,reference({seed:19}),'tile timeout fallback');assert(tileHang.failures.some(f=>f.error.includes('tile timeout')),'tile timeout recorded');records.push('tile timeout');
 const unavailable=pool(1,{WorkerClass:null});await unavailable.ready();await rejects(unavailable.render({seed:0}),'No rendering worker');const missingFallback=pool(1,{WorkerClass:null,fallback:reference});await missingFallback.ready();equal((await missingFallback.render({seed:9})).pixels,reference({seed:9}),'no Worker fallback');records.push('unavailable workers with/without explicit fallback');
 const dispose=pool(1);await dispose.ready();const pending=dispose.render({seed:2,delay:100});dispose.dispose();assert((await pending).reason==='disposed','disposed pending');await rejects(dispose.render({seed:2}),'disposed');await rejects(four.render({seed:3,notCloneable:()=>{}}),'could not be cloned');records.push('disposal and clone rejection');
 const bend1=pool(1,{taskModule:window.__bendFixtureURL}),bend4=pool(4,{taskModule:window.__bendFixtureURL});assert((await bend1.ready()).workers===1,'Bend worker init');assert((await bend4.ready()).workers===4,'Bend worker init4');const [b1,b4]=await Promise.all([bend1.render({}),bend4.render({})]);equal(b1.pixels,b4.pixels,'compiled Bend worker scheduling');const native=new Uint8Array(4096);window.__nativePixels.forEach((rgb,i)=>native.set([rgb>>>16&255,rgb>>>8&255,rgb&255,255],i*4));equal(b1.pixels,native,'compiled Bend browser/native complete pixels');records.push('actual compiled Bend inside 1/4 workers equals native fixture pixels');
 window.__qa={ok:true,groups:records,comparedBytes,nativeBendPixels:1024,bendWorkers:[b1.metrics,b4.metrics],environment:location.protocol==='http:'?'Real module workers and compiled Bend via loopback static HTTP; no GPU execution.':'Real module workers with rebased data-URL fixtures; no HTTP deployment or GPU execution.'};
}finally{for(const p of pools)p.dispose();}
